export interface Country {
  slug: string;
  name: string;
  flag: string;
  catholicPop: string;
  headline: string;
  description: string;
  whyPoints: { icon: string; title: string; desc: string }[];
  cities: string[];
  testimonial?: { quote: string; name: string; location: string; initial: string };
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  schemaArea: string;
}

export const countries: Country[] = [
  {
    slug: "catholic-dating-brazil",
    name: "Brazil",
    flag: "🇧🇷",
    catholicPop: "105 million Catholics",
    headline: "Catholic Dating in Brazil — Encontre Seu Parceiro de Fé",
    description: "Brazil has the largest Catholic population on earth — over 105 million faithful. CatholicBond connects verified Brazilian Catholic singles across São Paulo, Rio de Janeiro, Belo Horizonte, and every state, within a community that takes faith, family, and marriage seriously.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Perfis Verificados", desc: "Every Brazilian member completes photo verification. Real people, real faith — no fake profiles, no wasted time." },
      { icon: "bi-heart-fill", title: "Matching Mútuo", desc: "Connections are only made when both people express interest. No one-sided pressure — pure, mutual intent." },
      { icon: "bi-patch-check-fill", title: "Distintivo de Fé", desc: "Pass our Catholic faith quiz to earn a badge. Show your commitment visibly to every potential match." },
      { icon: "bi-people-fill", title: "Maior Comunidade Católica", desc: "Brazil's Catholic community is the world's largest. CatholicBond brings the best of it into one trusted space." },
    ],
    cities: ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Salvador", "Fortaleza", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Brasília", "Goiânia", "Belém"],
    metaTitle: "Catholic Dating Brazil — Meet Verified Brazilian Catholic Singles",
    metaDescription: "Meet verified Brazilian Catholic singles on CatholicBond. Photo-verified profiles, faith quiz badges, and mutual matching. Join Brazil's largest Catholic dating community. Free to download.",
    keywords: ["Catholic dating Brazil", "Brazilian Catholic singles", "Catholic dating São Paulo", "Catholic singles Rio de Janeiro", "namoro católico Brasil"],
    schemaArea: "Brazil",
  },
  {
    slug: "catholic-dating-mexico",
    name: "Mexico",
    flag: "🇲🇽",
    catholicPop: "91 million Catholics",
    headline: "Catholic Dating in Mexico — Amor Basado en la Fe",
    description: "Mexico is home to 91 million Catholics — one of the most devout nations on earth. CatholicBond connects verified Mexican Catholic singles across Mexico City, Guadalajara, Monterrey, and every state, in a community built on shared faith and the call to holy matrimony.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Perfiles Verificados", desc: "Every Mexican member verifies their identity with a real-time selfie. No fake profiles — a genuine, safe community." },
      { icon: "bi-patch-check-fill", title: "Insignia de Fe", desc: "Complete our Catholic faith quiz and earn a badge that signals your knowledge and commitment to potential matches." },
      { icon: "bi-heart-fill", title: "Conexiones Intencionales", desc: "Every member is here for intentional connection, not casual swiping. A community that takes vocation seriously." },
      { icon: "bi-star-fill", title: "Membresía Premium", desc: "Upgrade to unlock unlimited messaging and a gold cross badge that helps you stand out in the community." },
    ],
    cities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Ciudad Juárez", "Zapopan", "Mérida", "San Luis Potosí", "Querétaro", "Aguascalientes"],
    metaTitle: "Catholic Dating Mexico — Meet Verified Mexican Catholic Singles",
    metaDescription: "Meet verified Mexican Catholic singles on CatholicBond. Faith-centred matching, photo verification, and a free tier. Join Mexico's growing Catholic dating community. Download free.",
    keywords: ["Catholic dating Mexico", "Mexican Catholic singles", "Catholic dating Mexico City", "citas católicas México", "solteros católicos México"],
    schemaArea: "Mexico",
  },
  {
    slug: "catholic-dating-philippines",
    name: "Philippines",
    flag: "🇵🇭",
    catholicPop: "93 million Catholics",
    headline: "Catholic Dating in the Philippines — Find Love Grounded in Faith",
    description: "The Philippines is the largest Catholic country in Asia, with over 93 million faithful. CatholicBond connects verified Filipino Catholic singles across Manila, Cebu, Davao, and every island — in a community that understands the Filipino Catholic culture of family, devotion, and intentional courtship.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every Filipino member verifies with a real-time selfie. Safe, authentic, and free from fake profiles." },
      { icon: "bi-people-fill", title: "Filipino Catholic Values", desc: "CatholicBond understands Filipino Catholic culture — the importance of family approval, novenas, and parish life." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Demonstrate your Catholic knowledge with a badge on your profile — a signal Filipino Catholics recognise and respect." },
      { icon: "bi-heart-fill", title: "Serious Relationships Only", desc: "Every member is here to discern marriage — not casual connections. Just as your faith calls you to be." },
    ],
    cities: ["Manila", "Quezon City", "Cebu", "Davao", "Caloocan", "Zamboanga", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro", "Parañaque", "Makati"],
    testimonial: { quote: "I never thought I'd find someone who shared my devotion to Our Lady of Perpetual Help. On CatholicBond I met my partner through a genuine conversation about the faith. We are now engaged.", name: "Maria R.", location: "Manila, Philippines", initial: "M" },
    metaTitle: "Catholic Dating Philippines — Meet Verified Filipino Catholic Singles",
    metaDescription: "Meet verified Filipino Catholic singles on CatholicBond — Asia's largest Catholic dating app. Photo-verified profiles, faith quiz badges. Free to download on iOS and Android.",
    keywords: ["Catholic dating Philippines", "Filipino Catholic singles", "Catholic dating Manila", "Catholic singles Cebu", "Catholic dating app Philippines"],
    schemaArea: "Philippines",
  },
  {
    slug: "catholic-dating-usa",
    name: "United States",
    flag: "🇺🇸",
    catholicPop: "69 million Catholics",
    headline: "Catholic Dating in the USA — Find Your Faith Partner Across America",
    description: "Over 69 million Americans identify as Catholic. CatholicBond connects verified Catholic singles across New York, Los Angeles, Chicago, Houston, and every state — in a faith-centred community built for intentional, marriage-focused relationships.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every American member verifies their identity. Real Catholics, real intent — no catfishing, no wasted conversations." },
      { icon: "bi-people-fill", title: "National Reach", desc: "From the Northeast to the Bible Belt, from California to Florida — CatholicBond connects Catholics coast to coast." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Earn a badge that signals your Catholic formation — respected by the serious singles you want to attract." },
      { icon: "bi-chat-heart-fill", title: "Intentional Messaging", desc: "Free members send one thoughtful message daily. Premium unlocks unlimited conversations with your matches." },
    ],
    cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "Boston", "Miami", "Dallas", "San Diego", "San Francisco"],
    metaTitle: "Catholic Dating USA — Meet Verified American Catholic Singles",
    metaDescription: "Meet verified Catholic singles across the United States on CatholicBond. Photo-verified profiles, faith quiz badges, and a free tier. The best Catholic dating app for serious relationships. Download free.",
    keywords: ["Catholic dating USA", "American Catholic singles", "Catholic dating app United States", "Catholic singles New York", "Catholic dating Chicago"],
    schemaArea: "United States",
  },
  {
    slug: "catholic-dating-congo",
    name: "DR Congo",
    flag: "🇨🇩",
    catholicPop: "55 million Catholics",
    headline: "Catholic Dating in DR Congo — Foi, Amour et Mariage",
    description: "The Democratic Republic of Congo leads Africa with nearly 55 million Catholics — the fastest-growing Catholic community on the continent. CatholicBond connects verified Congolese Catholic singles across Kinshasa, Lubumbashi, and every province, in a faith community that is alive, growing, and serious about marriage.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Profils Vérifiés", desc: "Every Congolese member verifies with a selfie. A genuine, safe community free from fake profiles." },
      { icon: "bi-people-fill", title: "Plus Grande Église d'Afrique", desc: "DRC has Africa's largest and fastest-growing Catholic community. CatholicBond connects you with the best of it." },
      { icon: "bi-heart-fill", title: "Connexions Sérieuses", desc: "Every member is here to discern marriage. No casual swiping — just Catholics committed to their faith and vocation." },
      { icon: "bi-patch-check-fill", title: "Badge de Foi", desc: "Pass our Catholic faith quiz and display your badge — a visible signal of your commitment to potential matches." },
    ],
    cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu", "Tshikapa", "Kolwezi", "Likasi", "Goma", "Matadi", "Uvira"],
    metaTitle: "Catholic Dating DR Congo — Meet Verified Congolese Catholic Singles",
    metaDescription: "Meet verified Congolese Catholic singles on CatholicBond. Africa's fastest-growing Catholic community. Photo-verified profiles, faith quiz badges. Free to download.",
    keywords: ["Catholic dating Congo", "Congolese Catholic singles", "Catholic dating Kinshasa", "rencontre catholique Congo", "solteiros católicos Congo"],
    schemaArea: "Democratic Republic of the Congo",
  },
  {
    slug: "catholic-dating-italy",
    name: "Italy",
    flag: "🇮🇹",
    catholicPop: "50 million Catholics",
    headline: "Catholic Dating in Italy — Amore Fondato sulla Fede",
    description: "Italy — the heart of the Catholic Church and home to 50 million faithful — is where faith and love have always been inseparable. CatholicBond connects verified Italian Catholic singles across Rome, Milan, Naples, and every region, in a community that honours the depth of the Italian Catholic tradition.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Profili Verificati", desc: "Every Italian member completes photo verification. A genuine, trustworthy community without fake profiles." },
      { icon: "bi-patch-check-fill", title: "Distintivo di Fede", desc: "Pass our Catholic faith quiz and earn a badge that shows your formation and commitment to the faith." },
      { icon: "bi-heart-fill", title: "Solo Relazioni Serie", desc: "CatholicBond is for Catholics who take their vocation seriously. Every member is here with intention." },
      { icon: "bi-people-fill", title: "Comunità Globale", desc: "Connect with Italian Catholics at home and across the diaspora — in London, New York, Sydney, and beyond." },
    ],
    cities: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Catania", "Venice", "Verona", "Messina"],
    metaTitle: "Catholic Dating Italy — Meet Verified Italian Catholic Singles",
    metaDescription: "Meet verified Italian Catholic singles on CatholicBond. Photo-verified profiles, faith quiz badges, mutual matching. Join the faith-centred dating community rooted in Italian Catholic tradition. Free to download.",
    keywords: ["Catholic dating Italy", "Italian Catholic singles", "incontri cattolici Italia", "Catholic dating Rome", "Catholic singles Milan"],
    schemaArea: "Italy",
  },
  {
    slug: "catholic-dating-france",
    name: "France",
    flag: "🇫🇷",
    catholicPop: "40 million Catholics",
    headline: "Catholic Dating in France — L'Amour Fondé sur la Foi",
    description: "France has 40 million Catholics — and a rich tradition of faith, from the pilgrimages of Lourdes to the cathedrals of Paris. CatholicBond connects verified French Catholic singles across Paris, Lyon, Marseille, and every region, in a community that takes the Catholic vision of love and marriage seriously.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Profils Vérifiés", desc: "Every French member verifies with a real-time selfie. Authentic, trustworthy connections only." },
      { icon: "bi-heart-fill", title: "Rencontres Intentionnelles", desc: "A space for Catholics who are serious about discerning marriage — not casual encounters." },
      { icon: "bi-patch-check-fill", title: "Badge de Foi", desc: "Earn a badge by passing our Catholic faith quiz. Signal your knowledge and values to compatible singles." },
      { icon: "bi-people-fill", title: "Communauté Mondiale", desc: "Connect with French Catholics at home and across the diaspora in Belgium, Canada, and Switzerland." },
    ],
    cities: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims"],
    metaTitle: "Catholic Dating France — Meet Verified French Catholic Singles",
    metaDescription: "Meet verified French Catholic singles on CatholicBond. Rencontres catholiques avec vérification photo et matching mutuel. Free to download on iOS and Android.",
    keywords: ["Catholic dating France", "French Catholic singles", "rencontre catholique France", "Catholic dating Paris", "solteros católicos Francia"],
    schemaArea: "France",
  },
  {
    slug: "catholic-dating-colombia",
    name: "Colombia",
    flag: "🇨🇴",
    catholicPop: "36 million Catholics",
    headline: "Catholic Dating in Colombia — Amor Construido en la Fe",
    description: "Colombia is home to 36 million Catholics — a deeply devout nation where faith shapes family life, culture, and community. CatholicBond connects verified Colombian Catholic singles across Bogotá, Medellín, Cali, and every department, in a community built on the shared Catholic values of faith, family, and holy matrimony.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Perfiles Verificados", desc: "Foto-verificación en cada perfil. Comunidad auténtica sin perfiles falsos." },
      { icon: "bi-heart-fill", title: "Solo Relaciones Serias", desc: "Cada miembro busca discernir el matrimonio. Sin conexiones casuales — solo intención real." },
      { icon: "bi-patch-check-fill", title: "Insignia de Fe", desc: "Gana una insignia al completar nuestro cuestionario de fe católica. Destácate con los valores correctos." },
      { icon: "bi-people-fill", title: "Comunidad Global", desc: "Conéctate con colombianos católicos en Colombia y en la diáspora en EE.UU., España y más." },
    ],
    cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Ibagué", "Pasto", "Manizales"],
    metaTitle: "Catholic Dating Colombia — Meet Verified Colombian Catholic Singles",
    metaDescription: "Meet verified Colombian Catholic singles on CatholicBond. Citas católicas con verificación de foto e insignia de fe. Gratis para descargar en iOS y Android.",
    keywords: ["Catholic dating Colombia", "citas católicas Colombia", "solteros católicos Colombia", "Catholic dating Bogotá", "Catholic singles Medellín"],
    schemaArea: "Colombia",
  },
  {
    slug: "catholic-dating-spain",
    name: "Spain",
    flag: "🇪🇸",
    catholicPop: "33 million Catholics",
    headline: "Catholic Dating in Spain — El Amor Enraizado en la Fe",
    description: "Spain — the land of Camino de Santiago, Ignatius of Loyola, and Teresa of Ávila — has 33 million Catholics steeped in one of the world's richest Catholic traditions. CatholicBond connects verified Spanish Catholic singles across Madrid, Barcelona, Seville, and every province, in a community that takes faith and marriage seriously.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Perfiles Verificados", desc: "Verificación fotográfica en cada perfil. Sin perfiles falsos — solo católicos reales." },
      { icon: "bi-patch-check-fill", title: "Insignia de Fe", desc: "Supera nuestro cuestionario de fe y gana un distintivo que señala tu formación y compromiso." },
      { icon: "bi-heart-fill", title: "Intencionalidad", desc: "Una comunidad para quien busca discernir el matrimonio con seriedad y fe." },
      { icon: "bi-people-fill", title: "Diáspora Española", desc: "Conéctate con católicos españoles en España, América Latina y todo el mundo." },
    ],
    cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba"],
    metaTitle: "Catholic Dating Spain — Meet Verified Spanish Catholic Singles",
    metaDescription: "Meet verified Spanish Catholic singles on CatholicBond. Citas católicas con verificación de foto. La app de citas católicas más seria de España. Gratis para descargar.",
    keywords: ["Catholic dating Spain", "citas católicas España", "solteros católicos España", "Catholic dating Madrid", "Catholic singles Barcelona"],
    schemaArea: "Spain",
  },
  {
    slug: "catholic-dating-argentina",
    name: "Argentina",
    flag: "🇦🇷",
    catholicPop: "31 million Catholics",
    headline: "Catholic Dating in Argentina — Fe, Amor y Matrimonio",
    description: "Argentina — home of Pope Francis and 31 million Catholics — has a Catholic identity woven into its national soul. CatholicBond connects verified Argentine Catholic singles across Buenos Aires, Córdoba, Rosario, and every province, in a community that reflects the deep Argentine Catholic devotion to faith and family.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Perfiles Verificados", desc: "Verificación en tiempo real con selfie. Sin perfiles falsos, sin tiempo perdido." },
      { icon: "bi-heart-fill", title: "Matrimonio Primero", desc: "Cada miembro busca una relación seria fundada en la fe — exactamente como lo llama la Iglesia." },
      { icon: "bi-patch-check-fill", title: "Insignia de Fe", desc: "Completa el cuestionario de fe y muestra tu compromiso con un distintivo en tu perfil." },
      { icon: "bi-people-fill", title: "Tierra del Papa Francisco", desc: "Argentina es la nación del Santo Padre. CatholicBond honra esa herencia de fe." },
    ],
    cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Santiago del Estero"],
    metaTitle: "Catholic Dating Argentina — Meet Verified Argentine Catholic Singles",
    metaDescription: "Meet verified Argentine Catholic singles on CatholicBond. Citas católicas con verificación foto e insignia de fe. Gratis para descargar en iOS y Android.",
    keywords: ["Catholic dating Argentina", "citas católicas Argentina", "solteros católicos Argentina", "Catholic dating Buenos Aires"],
    schemaArea: "Argentina",
  },
  {
    slug: "catholic-dating-poland",
    name: "Poland",
    flag: "🇵🇱",
    catholicPop: "33 million Catholics",
    headline: "Catholic Dating in Poland — Miłość Zakorzeniona w Wierze",
    description: "Poland is one of the most devout Catholic nations in Europe, with 33 million faithful and a faith tradition shaped by John Paul II, Faustina Kowalska, and Maximilian Kolbe. CatholicBond connects verified Polish Catholic singles across Warsaw, Kraków, Gdańsk, and every voivodeship, in a community built on deep Catholic conviction.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Zweryfikowane Profile", desc: "Każdy członek weryfikuje tożsamość w czasie rzeczywistym. Prawdziwi katolicy, prawdziwe intencje." },
      { icon: "bi-patch-check-fill", title: "Odznaka Wiary", desc: "Zdaj quiz z wiedzy katolickiej i zdobądź odznakę widoczną na Twoim profilu." },
      { icon: "bi-heart-fill", title: "Poważne Związki", desc: "Każdy użytkownik szuka rozeznania powołania do małżeństwa — tak jak Kościół nas wzywa." },
      { icon: "bi-people-fill", title: "Globalna Diaspora", desc: "Połącz się z polskimi katolikami w Polsce i diasporze — w UK, Niemczech i USA." },
    ],
    cities: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Białystok", "Katowice", "Rzeszów"],
    metaTitle: "Catholic Dating Poland — Meet Verified Polish Catholic Singles",
    metaDescription: "Meet verified Polish Catholic singles on CatholicBond. Randki katolickie z weryfikacją zdjęcia i odznaką wiary. Free to download on iOS and Android.",
    keywords: ["Catholic dating Poland", "Polish Catholic singles", "randki katolickie Polska", "Catholic dating Warsaw", "Catholic singles Kraków"],
    schemaArea: "Poland",
  },
  {
    slug: "catholic-dating-kenya",
    name: "Kenya",
    flag: "🇰🇪",
    catholicPop: "9 million Catholics",
    headline: "Catholic Dating in Kenya — Faith-Centred Love Across East Africa",
    description: "Kenya has a vibrant and growing Catholic community — one of the most active in East Africa. CatholicBond connects verified Kenyan Catholic singles across Nairobi, Mombasa, Kisumu, and every county, in a community that understands the Kenyan Catholic culture of faith, family, and intentional relationships.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every Kenyan member verifies their identity with a selfie. Authentic connections, no fake profiles." },
      { icon: "bi-people-fill", title: "East African Community", desc: "Connect with Kenyan and East African Catholic singles at home and across the diaspora." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Pass our Catholic faith quiz and show your commitment with a badge on your profile." },
      { icon: "bi-heart-fill", title: "Marriage-Focused", desc: "Every member is here to discern serious, faith-centred relationships — not casual connections." },
    ],
    cities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Kakamega", "Nyeri", "Meru"],
    metaTitle: "Catholic Dating Kenya — Meet Verified Kenyan Catholic Singles",
    metaDescription: "Meet verified Kenyan Catholic singles on CatholicBond. Photo-verified profiles, faith quiz badges, and mutual matching. Join East Africa's Catholic dating community. Free to download.",
    keywords: ["Catholic dating Kenya", "Kenyan Catholic singles", "Catholic dating Nairobi", "Catholic singles Kenya", "Catholic dating app Kenya"],
    schemaArea: "Kenya",
  },
  {
    slug: "catholic-dating-uganda",
    name: "Uganda",
    flag: "🇺🇬",
    catholicPop: "17 million Catholics",
    headline: "Catholic Dating in Uganda — Faith, Family and Holy Matrimony",
    description: "Uganda — home of the Uganda Martyrs and 17 million Catholics — has one of the most spiritually alive Catholic communities in Africa. CatholicBond connects verified Ugandan Catholic singles across Kampala, Entebbe, Gulu, and every district, in a community worthy of that great tradition.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every Ugandan member verifies their identity. A safe, genuine community for real Catholics." },
      { icon: "bi-people-fill", title: "Land of the Martyrs", desc: "Uganda's Catholic heritage is unmatched in Africa. CatholicBond honours that legacy of faith and sacrifice." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Earn a badge by passing our faith quiz — a sign of formation and Catholic knowledge." },
      { icon: "bi-heart-fill", title: "Intentional Courtship", desc: "A community for Ugandan Catholics who approach relationships with prayer, patience, and purpose." },
    ],
    cities: ["Kampala", "Gulu", "Entebbe", "Lira", "Mbarara", "Jinja", "Mbale", "Fort Portal", "Arua", "Soroti", "Masaka", "Hoima"],
    metaTitle: "Catholic Dating Uganda — Meet Verified Ugandan Catholic Singles",
    metaDescription: "Meet verified Ugandan Catholic singles on CatholicBond. The faith-centred dating app for Uganda's Catholic community. Photo-verified profiles. Free to download.",
    keywords: ["Catholic dating Uganda", "Ugandan Catholic singles", "Catholic dating Kampala", "Catholic singles Uganda", "Uganda Catholic dating app"],
    schemaArea: "Uganda",
  },
  {
    slug: "catholic-dating-tanzania",
    name: "Tanzania",
    flag: "🇹🇿",
    catholicPop: "12 million Catholics",
    headline: "Catholic Dating in Tanzania — Upendo Uliojengwa katika Imani",
    description: "Tanzania has 12 million Catholics and one of the most dynamic Catholic communities in East Africa. CatholicBond connects verified Tanzanian Catholic singles across Dar es Salaam, Mwanza, Arusha, and every region, in a faith-centred community built for serious, marriage-focused relationships.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Uthibitisho wa Picha", desc: "Every Tanzanian member verifies their identity. Real Catholics only — no fake profiles." },
      { icon: "bi-heart-fill", title: "Ndoa ya Kweli", desc: "Every member is discerning marriage seriously. A community aligned with the Church's vision of love." },
      { icon: "bi-patch-check-fill", title: "Beji ya Imani", desc: "Pass our Catholic faith quiz and display your badge — a signal of your commitment and formation." },
      { icon: "bi-people-fill", title: "Jumuiya ya Afrika Mashariki", desc: "Connect with Tanzanian and East African Catholics across the region and diaspora." },
    ],
    cities: ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Morogoro", "Tanga", "Kahama", "Zanzibar", "Kigoma", "Tabora", "Shinyanga"],
    metaTitle: "Catholic Dating Tanzania — Meet Verified Tanzanian Catholic Singles",
    metaDescription: "Meet verified Tanzanian Catholic singles on CatholicBond. The faith-centred Catholic dating app for Tanzania. Photo-verified profiles. Free to download on iOS and Android.",
    keywords: ["Catholic dating Tanzania", "Tanzanian Catholic singles", "Catholic dating Dar es Salaam", "Catholic singles Tanzania"],
    schemaArea: "Tanzania",
  },
  {
    slug: "catholic-dating-india",
    name: "India",
    flag: "🇮🇳",
    catholicPop: "23 million Catholics",
    headline: "Catholic Dating in India — Find Your Faith Partner Across India",
    description: "India has 23 million Catholics — a vibrant minority with deep roots in Goa, Kerala, Tamil Nadu, and across the nation. CatholicBond connects verified Indian Catholic singles across Mumbai, Goa, Kochi, Chennai, and every state, in a community that honours the rich Indian Catholic tradition of faith and family.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every Indian member verifies their identity with a selfie. Authentic, safe, and free from fake profiles." },
      { icon: "bi-people-fill", title: "Kerala & Goa Heritage", desc: "CatholicBond understands the distinct Catholic cultures of Kerala, Goa, Tamil Nadu, and the Northeast." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Earn a badge that signals your Catholic formation — respected across every Indian Catholic community." },
      { icon: "bi-heart-fill", title: "Family-Centred Values", desc: "A community that understands the Indian Catholic emphasis on family, faith, and the sacrament of marriage." },
    ],
    cities: ["Mumbai", "Goa", "Kochi", "Chennai", "Mangalore", "Bengaluru", "Pune", "Delhi", "Hyderabad", "Kolkata", "Shillong", "Nagpur"],
    metaTitle: "Catholic Dating India — Meet Verified Indian Catholic Singles",
    metaDescription: "Meet verified Indian Catholic singles on CatholicBond. Photo-verified profiles for Kerala, Goa, Tamil Nadu Catholics and all of India. Free to download on iOS and Android.",
    keywords: ["Catholic dating India", "Indian Catholic singles", "Catholic dating Kerala", "Catholic singles Goa", "Catholic dating Mumbai"],
    schemaArea: "India",
  },
  {
    slug: "catholic-dating-ghana",
    name: "Ghana",
    flag: "🇬🇭",
    catholicPop: "5 million Catholics",
    headline: "Catholic Dating in Ghana — Faith-Centred Love in West Africa",
    description: "Ghana has a growing and dynamic Catholic community, deeply embedded in the nation's social and spiritual life. CatholicBond connects verified Ghanaian Catholic singles across Accra, Kumasi, Tamale, and every region, in a community built on the shared values of faith, family, and holy matrimony.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every Ghanaian member verifies their identity. A safe, genuine community for real Ghanaian Catholics." },
      { icon: "bi-heart-fill", title: "Faith & Family First", desc: "CatholicBond understands the Ghanaian Catholic emphasis on family life, parish community, and marriage." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Pass our Catholic faith quiz and earn a badge that signals your commitment and formation." },
      { icon: "bi-people-fill", title: "Diaspora Connections", desc: "Connect with Ghanaian Catholics in Ghana and across the diaspora in the UK, USA, and Europe." },
    ],
    cities: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Cape Coast", "Sunyani", "Koforidua", "Ho", "Wa", "Techiman", "Bolgatanga", "Tema"],
    metaTitle: "Catholic Dating Ghana — Meet Verified Ghanaian Catholic Singles",
    metaDescription: "Meet verified Ghanaian Catholic singles on CatholicBond. The faith-centred Catholic dating app for Ghana's Catholic community. Photo-verified profiles. Free to download.",
    keywords: ["Catholic dating Ghana", "Ghanaian Catholic singles", "Catholic dating Accra", "Catholic singles Ghana", "Catholic dating app Ghana"],
    schemaArea: "Ghana",
  },
  {
    slug: "catholic-dating-canada",
    name: "Canada",
    flag: "🇨🇦",
    catholicPop: "13 million Catholics",
    headline: "Catholic Dating in Canada — Find Meaningful Faith-Centred Love",
    description: "Canada has 13 million Catholics — a diverse community spanning French Canadians, Irish Catholics, a large Filipino and African diaspora, and more. CatholicBond connects verified Canadian Catholic singles across Toronto, Montreal, Vancouver, and every province, in one trusted, faith-centred space.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every Canadian member verifies their identity. A real, safe community across every province." },
      { icon: "bi-people-fill", title: "Diverse Catholic Canada", desc: "From Québec's historic Church to the Filipino Catholic diaspora in Ontario — CatholicBond connects all." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Earn your faith badge and stand out to the serious singles you're looking to meet." },
      { icon: "bi-heart-fill", title: "Intentional Relationships", desc: "Every member is here to discern marriage — not casual connections. Exactly what you deserve." },
    ],
    cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "London", "Halifax", "Saskatoon"],
    testimonial: { quote: "What I love most is the intentionality. The men here take their time and write thoughtfully. It felt completely different from every other dating app I have tried.", name: "Chisom E.", location: "Toronto, Canada", initial: "C" },
    metaTitle: "Catholic Dating Canada — Meet Verified Canadian Catholic Singles",
    metaDescription: "Meet verified Canadian Catholic singles on CatholicBond. Photo-verified profiles, faith quiz badges, and mutual matching across Toronto, Montreal, Vancouver and all of Canada. Download free.",
    keywords: ["Catholic dating Canada", "Canadian Catholic singles", "Catholic dating Toronto", "Catholic singles Montreal", "Catholic dating app Canada"],
    schemaArea: "Canada",
  },
  {
    slug: "catholic-dating-australia",
    name: "Australia",
    flag: "🇦🇺",
    catholicPop: "5 million Catholics",
    headline: "Catholic Dating in Australia — Faith-Centred Love Down Under",
    description: "Australia has 5 million Catholics — a vibrant community including Irish-Australians, Italians, Filipinos, and a growing African Catholic diaspora. CatholicBond connects verified Australian Catholic singles across Sydney, Melbourne, Brisbane, and every state, in a faith-centred space built for serious relationships.",
    whyPoints: [
      { icon: "bi-shield-check", title: "Photo Verification", desc: "Every Australian member verifies their identity. Authentic connections from Sydney to Perth." },
      { icon: "bi-people-fill", title: "Multicultural Catholic Community", desc: "Australia's Catholic Church is beautifully diverse — Irish, Italian, Filipino, African, and more, united in faith." },
      { icon: "bi-patch-check-fill", title: "Faith Quiz Badge", desc: "Earn your badge and signal your Catholic formation to serious singles across Australia." },
      { icon: "bi-heart-fill", title: "Serious About Marriage", desc: "Every member is here to discern a faith-centred relationship — no casual connections." },
    ],
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Sunshine Coast", "Wollongong", "Darwin", "Hobart"],
    metaTitle: "Catholic Dating Australia — Meet Verified Australian Catholic Singles",
    metaDescription: "Meet verified Australian Catholic singles on CatholicBond. Photo-verified profiles, faith quiz badges, and mutual matching across Sydney, Melbourne, Brisbane and all of Australia. Download free.",
    keywords: ["Catholic dating Australia", "Australian Catholic singles", "Catholic dating Sydney", "Catholic singles Melbourne", "Catholic dating app Australia"],
    schemaArea: "Australia",
  },
];
